name: my_expenses
description: "A financial app for my expenses"
publish_to: 'github'

version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.8
  intl: any
  sqflite: ^2.3.2
  path: ^1.8.3
  easy_pie_chart: ^1.0.0
  fl_chart: ^0.68.0
  carousel_slider: ^5.0.0
  path_provider: ^2.1.5
  csv: ^6.0.0
  open_filex: ^4.6.0
  social_sharing_plus: ^1.2.3
  flutter_native_splash: ^1.1.8+4
  flutter_launcher_icons: ^0.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter_native_splash:
  color: "#56aeff"
  image: assets/splash_icon.png
  android: true

flutter_icons:
  android: "ic_launcher"
  image_path: "assets/icons/icon.png"

flutter:

  uses-material-design: true

  assets:
    - assets/icons/cats_icon.png
    - assets/icons/compras_icon.png
    - assets/icons/mercado_icon.png
    - assets/icons/merenda_icon.png
    - assets/icons/meal_icon.png
    - assets/icons/home_icon.png
    - assets/icons/general_icon.png
    - assets/icons/reserva_icon.png
    - assets/icons/divided_icon.png
    - assets/icons/users_icon.png
    - assets/icons/pin_icon.png
